### ISSUE TITLE
[bug] `JSONDecodeError` if iperf3 is not installed on the device

### ISSUE THREAD

**Issue by Aryamanz29** [openwisp/openwisp-monitoring#412]
Reported by @nemesisdesign  in https://github.com/openwisp/openwisp-monitoring/pull/394#pullrequestreview-1031849801
### **Error :**
```bash
[2022-07-07 11:17:23,633: ERROR/ForkPoolWorker-1] Task openwisp_monitoring.check.tasks.perform_check[aabf00ea-3db9-4eaa-9076-8750eda2e7e3] raised unexpected: JSONDecodeError('Expecting value: line 2 column 1 (char 1)')
Traceback (most recent call last):
  File "/opt/openwisp2/env/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/openwisp_monitoring/check/tasks.py", line 48, in perform_check
    result = check.perform_check()
  File "/opt/openwisp2/env/lib/python3.9/site-packages/openwisp_monitoring/check/base/models.py", line 86, in perform_check
    return self.check_instance.check(store=True)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/openwisp_monitoring/check/classes/iperf.py", line 93, in check
    result_tcp = self._get_iperf_result(res, exit_code, device, mode='TCP')
  File "/opt/openwisp2/env/lib/python3.9/site-packages/openwisp_monitoring/check/classes/iperf.py", line 151, in _get_iperf_result
    res_dict = json.loads(res)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

It is happened because after executing `iperf_command` on the device it failed with **exit code : 127** _(Which means Either the command doesn't exist (package not installed), or the command isn't in your path ($PATH))_ and returned error is of type **string** instead of **dict**.

**Comment by nemesisdesign** [comment]
The right thing to do is to catch this exception and log a warning with the suggested cause and solution.
